# Generated by Django 5.0.6 on 2024-11-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_thesis_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='author',
            new_name='poster',
        ),
    ]
