# Generated by Django 5.0.6 on 2024-11-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_thesis_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='authors',
            field=models.TextField(max_length=255),
        ),
    ]
