# Generated by Django 5.0.6 on 2024-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_thesis_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
