# Generated by Django 5.0.6 on 2024-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_thesis_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
