# Generated by Django 5.0.6 on 2024-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_thesis_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
