# Generated by Django 5.0.6 on 2024-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_tempurl_pdf_file_alter_thesis_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='url_status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('USED', 'Used'), ('VALID', 'Valid')], default='VALID', max_length=10),
        ),
    ]
