# Generated by Django 5.0.6 on 2024-12-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_tempurl_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('APPOVED', 'Approved'), ('USED', 'Rejected'), ('VALID', 'Pending')], default='VALID', max_length=10),
        ),
    ]
