# Generated by Django 5.0.6 on 2024-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_thesis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='url_status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('USED', 'Used'), ('VALID', 'Valid'), ('REJECTED', 'Rejected')], default='VALID', max_length=10),
        ),
    ]
