# Generated by Django 5.0.6 on 2024-12-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_tempurl_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
