# Generated by Django 5.0.6 on 2024-12-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_tempurl_decision_date_alter_tempurl_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateField(),
        ),
    ]
