# Generated by Django 5.0.6 on 2024-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_tempurl_decision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='url_status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('USED', 'Used'), ('VALID', 'Valid'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('APPOVED', 'Approved'), ('USED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
