# Generated by Django 5.0.6 on 2024-12-29 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_tempurl_url_status_alter_thesis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='decision_date',
            field=models.DateField(default=datetime.date(2024, 12, 29)),
        ),
    ]
