# Generated by Django 5.0.6 on 2024-12-29 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_thesis_decision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 12, 29)),
        ),
    ]
