# Generated by Django 5.0.6 on 2024-12-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_tempurl_decision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='status',
            field=models.CharField(choices=[('APPOVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='url_status',
            field=models.CharField(choices=[('EXPIRED', 'Expired'), ('USED', 'Used'), ('VALID', 'Valid'), ('DOES NOT EXIST', 'Does Not Exist')], default='DOES NOT EXIST', max_length=15),
        ),
    ]
