# Generated by Django 5.0.6 on 2024-12-29 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_tempurl_status_alter_tempurl_url_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 29, 20, 53, 58, 309019)),
        ),
    ]
