# Generated by Django 5.0.6 on 2024-12-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_tempurl_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 20, 54, 40, 235296)),
        ),
    ]
