# Generated by Django 5.0.6 on 2024-12-29 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_tempurl_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateTimeField(default=datetime.date(2024, 12, 29)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 21, 28, 26, 847661)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
