# Generated by Django 5.0.6 on 2024-12-29 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_tempurl_decision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 22, 13, 10, 555924)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('USED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
