# Generated by Django 5.0.6 on 2025-01-05 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_tempurl_expiration_date_alter_tempurl_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 5)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 16, 4, 55, 83816)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='decision_date',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
    ]
