# Generated by Django 5.0.6 on 2025-01-05 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_thesis_rejection_reason_alter_tempurl_decision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 16, 10, 17, 620599)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
