# Generated by Django 5.0.6 on 2025-01-05 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_tempurl_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 18, 14, 57, 587914)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[(1, 'Incorrect Title.'), (2, 'Typographical Error in the name of one of more Author(s).'), (3, 'Problem in the Uploaded File'), (4, 'Incomplete Submission')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
