# Generated by Django 5.0.6 on 2025-01-05 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_tempurl_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 19, 35, 14, 737129)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('TITLE PROBLEM', 'Incorrect Title'), ('AUTHOR PROBLEM', 'Typographical Error in the name of one of more Author(s)'), ('FILE PROBLEM', 'Problem in the Uploaded File'), ('SUBMISSION PROBLEM', 'Incomplete Submission')], default='', max_length=50, null=True),
        ),
    ]
