# Generated by Django 5.0.6 on 2025-01-05 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_tempurl_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 20, 28, 18, 703145)),
        ),
    ]
