# Generated by Django 5.0.6 on 2025-01-05 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_tempurl_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 23, 7, 57, 965376)),
        ),
    ]
