# Generated by Django 5.0.6 on 2025-01-05 16:43

import datetime
import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_tempurl_expiration_date_alter_thesis_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='id_pic',
            field=models.ImageField(blank=True, null=True, upload_to='request_id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 6)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 0, 43, 34, 790500)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='decision_date',
            field=models.DateField(default=datetime.date(2025, 1, 6)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to=website.models.rename_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
