# Generated by Django 5.0.6 on 2025-01-05 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_tempurl_expiration_date_alter_tempurl_id_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempurl',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Invalid Email', 'Invalid Email is used'), ('Name Typo', 'Typographical Error in the name of the requestor'), ('Invalid File', 'Problem in the Uploaded File'), ('Blurred ID', 'ID Submitted is blurred/pixelated/unreadable')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 1, 30, 35, 575459)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('TITLE PROBLEM', 'Incorrect Title'), ('AUTHOR PROBLEM', 'Typographical Error in the name of one or more Author(s)'), ('FILE PROBLEM', 'Problem in the Uploaded File'), ('SUBMISSION PROBLEM', 'Incomplete Submission')], default='', max_length=50, null=True),
        ),
    ]
