# Generated by Django 5.0.6 on 2025-01-05 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_tempurl_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 1, 35, 34, 980695)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Invalid Email', 'Invalid Email is used'), ('Invalid Name', 'Typographical Error in the name of the requestor'), ('Invalid File', 'Problem in the Uploaded File'), ('Blurred ID', 'ID Submitted is blurred/pixelated/unreadable')], default='', max_length=50, null=True),
        ),
    ]
