# Generated by Django 5.0.6 on 2025-01-05 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_tempurl_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 2, 9, 36, 394462)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('Invalid Title', 'Incorrect Title was submitted'), ('Invalid Name', 'Typographical Error in the name of one or more Author(s)'), ('Invalid File', 'Problem with the Uploaded File'), ('Incomplete Detail', 'Information that was submitted was either incomplete or incorrect')], default='', max_length=50, null=True),
        ),
    ]
