# Generated by Django 5.0.6 on 2025-01-05 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_tempurl_expiration_date_alter_tempurl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 3, 27, 25, 78442)),
        ),
    ]
