# Generated by Django 5.0.6 on 2025-01-06 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_alter_tempurl_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempurl',
            name='decision_date',
            field=models.DateTimeField(default=datetime.date(2025, 1, 7)),
        ),
        migrations.AlterField(
            model_name='tempurl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 1, 48, 47, 475367)),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='decision_date',
            field=models.DateField(default=datetime.date(2025, 1, 7)),
        ),
    ]
